
# Royal Render Plugin config for Cinema R23+
# Last change: %rrVersion%
# Copyright (c)  Holger Schoenberger
# #win:   rrInstall_Copy:         plugins\
# #linux: rrInstall_Copy:         plugins\
# #mac:   rrInstall_Copy:         ..\plugins\
#
#
# IMPORTANT:
#    run 'workstationInstaller' on workstations, or update submission
#    plugins with rrControl, after editing this file.
#    Restart Cinema 4D, or run Extensions > Tools > Reload Python plugins
######################################################################

[SUBMISSION]
# Uncomment the following line (remove '#') to prevent RR from resolving $take with $parent-$take
# parent_in_take_token = 0

# Uncomment the following line (remove '#') to submit jobs to RR without showing submitter UI
# submit_ui = 0

