
IconApp=3D01__Softimage.png


################################## Submitter Settings ################################## 

#Settigs for the submitter
AllowLocalSceneCopy= 1~0
SceneFileExtension= *.scn
SequenceDivide= 1~1
AllowImageNameChange= 1
AllowImageDirChange= 1





################################## Client Settings ################################## 

Frozen_MinCoreUsage=1.90

TexReplaceFormat= .scn ~ Char ~ Both ~ .scntoc

licenseFailLine=  license available to run Softimage
licenseFailLine=  license available to run XSI

errorSearchLine=  try '-memory
errorSearchLine=  Error: Exit render because of missing texture file

permanentErrorSearchLine = Please try to load it from version
permanentErrorSearchLine = Student Version created file will not be loaded in batch mode

findFrameNoPre= Rendering frame 
findFrameNoPost=  (
findFrameNoPostLineSkip= skipped


RenderAppWindow_WIN= Microsoft Visual C++ Runtime Library ~ Runtime Error ~ 1 ~ Button ~ OK 
RenderAppWindow_WIN= XSI ~ Unable to access ~ 1 ~ Button ~ Cancel
RenderAppWindow_WIN= Import Multilight ~



::include(3D01__Softimage____global__inhouse.inc)


