 
IconApp=3D03__3dsMAX_s.png
ImageSizeCommandline= 	"*ResX*;;<Width>"  "*ResY*;;<Height>"

ImageSize= PAL  ~720~576
ImageSize= NTSC  ~720~486
ImageSize= HD 1080p ~ 1920~1080
ImageSize= HD 720p  ~ 1280~720
ImageSize= 4:3 Small ~ 400~300
ImageSize= 4:3 Big   ~ 1000~750
ImageSize= 16:9     ~ 1024~576


################################## Submitter Settings ################################## 
SceneFileExtension= *.max
AllowImageNameChange= 1
AllowImageDirChange= 1
SequenceDivide= 0~1
OverrideRendererPossible= 0
StartMultipleInstances=0~0
UIStyle= 1~dark


COhdrFrameBuffer= 1 ~ 1



################################## Client Settings ################################## 

Frozen_MinCoreUsage=1.90

licenseFailLine=  

errorSearchLine= Error executing render script
errorSearchLine= An unexpected exception has occurred in the network renderer and it is terminating
errorSearchLine= Unknown error while loading application
errorSearchLine= ERR: Timeout
errorSearchLine= bad allocation

permanentErrorSearchLine = Error initializing backburner path system



findFrameNoPre= Frame #
findFrameNoPost=  done

RenderAppWindow_WIN= Rendering - ~
RenderAppWindow_WIN= Rendern - ~
RenderAppWindow_WIN= - Autodesk 3ds Max ~
RenderAppWindow_WIN= MAXScript Debugger ~
RenderAppWindow_WIN= MAXScript-Debugger ~
RenderAppWindow_WIN= MAXScript Editor ~
RenderAppWindow_WIN= MAXScript-Editor ~
RenderAppWindow_WIN= RealFlow Log Window ~
RenderAppWindow_WIN= AfterBurn Shadow Map ~
RenderAppWindow_WIN= 3D Mouse News ~ ~ 1 ~ Button ~ Close
RenderAppWindow_WIN= Render history settings ~ The path ~ 1 ~ Button ~ &No
RenderAppWindow_WIN= GrowFX windows manager ~  ~ 1 ~ Button ~ OK 
RenderAppWindow_WIN= Render history ~
RenderAppWindow_WIN= Pixel information ~
RenderAppWindow_WIN= Stamp variables window ~
RenderAppWindow_WIN= Color corrections ~
RenderAppWindow_WIN= FumeFX ~
RenderAppWindow_WIN= DLL Initialization Fail ~ ~ 1 ~ Button ~ OK
RenderAppWindow_WIN= Error Report ~ ~ 1 ~ Button ~ Cancel
RenderAppWindow_WIN= Script Controller ~
RenderAppWindow_WIN= Rendering ~
RenderAppWindow_WIN= Interaction Mode ~ ~ 1 ~ Button ~ OK
RenderAppWindow_WIN= FFX_ ~
RenderAppWindow_WIN= Error ~ ~ 1 ~ Button ~ OK
RenderAppWindow_WIN= RFRK Log Window
RenderAppWindow_WIN= MXS_ ~
RenderAppWindow_WIN= State Sets ~
RenderAppWindow_WIN= .mcr - MAXScript ~
RenderAppWindow_WIN= Lens Effects ~
RenderAppWindow_WIN= Unhandled exception ~ ~ 1 ~ Button ~ &Abort
RenderAppWindow_WIN= Pencil+ ~
RenderAppWindow_WIN= Axis Constraints ~
RenderAppWindow_WIN= Render Shortcuts ~
RenderAppWindow_WIN= Snaps ~
RenderAppWindow_WIN= Animation Layers ~
RenderAppWindow_WIN= Layers ~
RenderAppWindow_WIN= Containers ~
RenderAppWindow_WIN= MassFX Toolbar ~
RenderAppWindow_WIN= Extras ~




RenderAppWindow_WIN= Maxwell Translation Window ~
RenderAppWindow_WIN= Maxwell Plug-in Update Notification ~ ~ 1 ~ Button ~ Don't notify me about this version automatically

RenderAppWindow_WIN= V-Ray Toolbar ~
RenderAppWindow_WIN= V-Ray frame buffer - ~
RenderAppWindow_WIN= Render history - ~
RenderAppWindow_WIN= Color corrections - ~
RenderAppWindow_WIN= Stamp variables window - ~

RenderAppWindow_WIN= Pixel information - ~
RenderAppWindow_WIN= Corona 5 | - ~


RemoveFromLog= Contains ~ MENTAL RAY LOG ~ loaded shader library
RemoveFromLog= Contains ~ MENTAL RAY LOG ~ parsing file




::include(3D03__3dsMAX_s____global__inhouse.inc)

