
IconApp=3D08__Modo.png


################################## Submitter Settings ################################## 

SceneFileExtension= *.lxo
SequenceDivide= 0~1
AllowLocalSceneCopy= 1~0


ImageSize= PAL  ~720~576
ImageSize= NTSC  ~720~486
ImageSize= HD  ~ 1920~1080
ImageSize= HD small  ~ 1280~720
ImageSize= 4:3 Small ~ 400~300
ImageSize= 4:3 Big   ~ 1000~750
ImageSize= 16:9     ~ 1024~576


################################## Client Settings ################################## 

Frozen_MinCoreUsage=1.90

TexReplaceFormat= .lxo ~ IFF4Item2 ~ OS

errorSearchLine=  script crashed
errorSearchLine=  Error reported


::include(3D08__Modo____global__inhouse.inc)


