# Last change: %rrVersion%

REZ_EXE_WIN=   modo_cl.exe
REZ_EXE_LX=    modo_cl
REZ_EXE_MAC=   modo_cl


IconApp=3D08__Modo.png


################################## Submitter Settings ################################## 

SceneFileExtension= *.lxo
SequenceDivide= 0~1
AllowLocalSceneCopy= 1~0




################################## Client Settings ################################## 

Frozen_MinCoreUsage=1.90

TexReplaceFormat= .lxo ~ IFF4Item2 ~ OS

errorSearchLine=  script crashed
errorSearchLine=  Error reported


::include(3D08__Modo____global__inhouse.inc)


