
AddPluginLicense=/Yeti

################################## Render Settings ################################## 


################################## Submitter Settings ################################## 
AllowImageNameChange= 1
AllowImageDirChange= 1
SequenceDivide= 0~1
AllowLocalSceneCopy= 0~0

################################## Client Settings ################################## 

IconApp=3D16__Katana.png


licenseFailLine=  No 'Render' license available
licenseFailLine=  License error
licenseFailLine=  All licenses in use

RealTimeAbortLine=  All licenses in use



errorSearchLine=  

permanentErrorSearchLine = invalid node type



::include(3D16__Katana____global__inhouse.inc)