

IconApp=3D21__UnrealEngine.png


################################## Submitter Settings ##################################
SequenceDivide= 0~1
SeqDivMIN=0~0
GPUrequired=0~1
AllowLocalSceneCopy= 0~0

################################## Client Settings ##################################

RemoveFromLog= StartsWith ~ ovr_Initialize failed: Unable to load LibOVRRT DLL 


::include(<ConfigFileName>__inhouse.inc)
