# Last change: %rrVersion%

IconApp=C13__Nuke.png

################################## Submitter Settings ################################## 
SceneFileExtension= *.nk
SequenceDivide= 0~1
AllowImageNameChange= 0
AllowImageDirChange= 0
RenderPreviewFirst= 0~0
UIStyle= 1~dark
MultiOSScenes=0~0
RequiredMemory=1~4
CONukeX= 1 ~ 0 

################################## Client Settings ################################## 

TexReplaceFormat= .nk ~ Char ~ AlwaysForward

licenseFailLine=  Did not find a valid license
licenseFailLine=  License failure
licenseFailLine=  FLEXlm : Error : Maximum user counted exceeded
licenseFailLine=  License system failed with error
licenseFailLine=  All licenses in use
licenseFailLine=  License request failed
licenseFailLine=  FOUNDRY LICENSE ERROR REPORT


permanentErrorSearchLine = Can't render from that Node
permanentErrorSearchLine = .nk is for nuke

findFrameNoPre= Writing 
findFrameNoPost= took

RemoveFromLog= Contains ~ Warning: Autosave file for


::include(C13__Nuke____global__inhouse.inc)


