# Last change: %rrVersion%



################################## Submitter Settings ################################## 
StartMultipleInstances= 0~0
SceneFileExtension= *.bat;*.sh;
AllowImageNameChange= 0
AllowImageDirChange= 0
SequenceDivide= 0~1





################################## Client Settings ################################## 

IconApp=E01__Execute.png

Frozen_MinCoreUsage=0.3
Frozen_Minutes=30


::include(E01__Execute____global__inhouse.inc)


