

################################## Submitter Settings ################################## 
StartMultipleInstances= 0~0
SceneFileExtension= *.py
AllowImageNameChange= 0
AllowImageDirChange= 0
SequenceDivide= 0~1
AllowLocalRenderOut= 0~0

COApplyPythonPathEnv= 1~0




################################## Client Settings ################################## 

IconApp=E02__Python.png

licenseFailLine=  

errorSearchLine=  

permanentErrorSearchLine = 

Frozen_MinCoreUsage=0.3
Frozen_Minutes=30




::include(E02__Python____global__inhouse.inc)


