

RendererLicense= /Arnold

IconRenderer=r_arnold.png

licenseFailLine=  abort_on_license_fail enabled
licenseFailLine=  abort_on_license_fail option is enabled

RealTimeAbortLine= abort_on_license_fail option is enabled

BrokenImageLine=  render terminating early


RemoveFromLog= Contains ~ |  lookdevkit_shaders.dll: 
RemoveFromLog= Contains ~ |  mtoa_shaders.dll: 
RemoveFromLog= Contains ~ |  renderSetup_shaders.dll: 
RemoveFromLog= Contains ~ |  cryptomatte.dll: 
RemoveFromLog= Contains ~ |  hairPhysicalShader_shaders.dll: 


::include(<ConfigFileName>__inhouse.inc)
