
GPUrequired= 0~1
Frozen_MinCoreUsage=0.30
IconRenderer=r_redshift.png



RealTimeAbortLine= Failed to init CUDA
RealTimeAbortLine= License subsystem failed to initialize
RealTimeAbortLine= Rendering aborted due to license check failure
RealTimeAbortLine= Redshift cannot operate
RealTimeAbortLine= Redshift is currently disabled
RealTimeAbortLine= Writing Redshift crash dump
RealTimeAbortLine= CL_OUT_OF_RESOURCES 
RealTimeAbortLine= CL_MEM_OBJECT_ALLOCATION_FAILURE 
RealTimeAbortLine= Output file locked or path not available for writing. Skipping frame


::include(<ConfigFileName>__inhouse.inc)
