//  Render script for Maya    
// Last Change: %rrVersion%
//  Copyright (c)  Holger Schoenberger - Binary Alchemy


global proc rrStartWrapper(string $pythonPath, string $args )
{	
    python("import sys");
    python("sys.path.append('"+$pythonPath+"')");
    python("import kso_maya");
    python("kso_maya.rrStart('"+$args+"')");
    python("sys.stdout.flush()");
    python("sys.stderr.flush()");
}

